# Generated by Django 6.0.5 on 2026-05-19 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo_cafe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipocafe')),
            ],
            options={
                'verbose_name': 'Precio Diario',
                'verbose_name_plural': 'Precios Diarios',
                'ordering': ['-fecha'],
                'unique_together': {('tipo_cafe', 'fecha')},
            },
        ),
    ]
