# Generated by Django 6.0.5 on 2026-06-03 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuenta', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor_nombre', models.CharField(max_length=200)),
                ('conductor_cedula', models.CharField(max_length=50)),
                ('conductor_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('conductor_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('vehiculo_clase', models.CharField(blank=True, max_length=100, null=True)),
                ('vehiculo_placas', models.CharField(max_length=20)),
                ('vehiculo_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('vehiculo_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehiculo_modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('flete_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('flete_pagadero_por', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_kilo_jefe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bultos', models.PositiveIntegerField(default=0)),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('tipo_cafe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipocafe')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
