# Generated by Django 6.0.5 on 2026-06-13 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='flete_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fletes_venta', to='caja.caja'),
        ),
        migrations.AddField(
            model_name='venta',
            name='flete_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
