# Generated by Django 6.0.5 on 2026-06-22 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        ('inventario', '0002_costoinventario'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetraCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_abonado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letras_cambio', to='inventario.bodega')),
                ('caficultor', models.ForeignKey(limit_choices_to={'tipo__in': ['caficultor', 'ambos']}, on_delete=django.db.models.deletion.PROTECT, related_name='letras_cambio', to='terceros.tercero')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letras_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letra de cambio',
                'verbose_name_plural': 'Letras de cambio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AbonoLetra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_letra', to='compras.compra')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_letra_creados', to=settings.AUTH_USER_MODEL)),
                ('letra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='letras_cambio.letracambio')),
            ],
            options={
                'verbose_name': 'Abono a letra',
                'verbose_name_plural': 'Abonos a letras',
                'ordering': ['-fecha'],
            },
        ),
    ]
