# Generated by Django 6.0.5 on 2026-06-14 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos_actuales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_actual', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_inventario', to='inventario.bodega')),
                ('tipo_cafe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_inventario', to='inventario.tipocafe')),
            ],
            options={
                'verbose_name': 'Costo de Inventario',
                'verbose_name_plural': 'Costos de Inventario',
                'unique_together': {('bodega', 'tipo_cafe')},
            },
        ),
    ]
