# Generated by Django 6.0.5 on 2026-09-11 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_costoinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos_antes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilos_despues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilos_ajuste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_stock', to='inventario.bodega')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajuste_stock', to='inventario.movimientoinventario')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_stock', to=settings.AUTH_USER_MODEL)),
                ('tipo_cafe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_stock', to='inventario.tipocafe')),
            ],
            options={
                'verbose_name': 'Ajuste de Stock',
                'verbose_name_plural': 'Ajustes de Stock',
                'ordering': ['-fecha'],
            },
        ),
    ]