# Generated by Django 6.0.5 on 2026-06-22 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_caja_abierta_cierrecaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='caja.caja')),
                ('caja_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='caja.caja')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_dinero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traslado de Dinero',
                'verbose_name_plural': 'Traslados de Dinero',
                'ordering': ['-creado_en'],
            },
        ),
    ]
