# Generated by Django 6.0.5 on 2026-06-03 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_deposito', models.BooleanField(default=False)),
                ('liquidado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_kilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Liquidación de Depósito',
                'verbose_name_plural': 'Liquidaciones de Depósito',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caficultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha'],
            },
        ),
    ]
