# Generated by Django 6.0.5 on 2026-06-03 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='tipo_cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipocafe'),
        ),
        migrations.AddField(
            model_name='liquidaciondeposito',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidaciondeposito',
            name='detalle_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='compras.detallecompra'),
        ),
    ]
