# Generated by Django 6.0.5 on 2026-05-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='es_deposito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='liquidado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_kilo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='LiquidacionDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_kilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='compras.detallecompra')),
            ],
            options={
                'verbose_name': 'Liquidación de Depósito',
                'verbose_name_plural': 'Liquidaciones de Depósito',
                'ordering': ['-fecha'],
            },
        ),
    ]
