# Generated by Django 6.0.5 on 2026-05-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_detallecompra_es_deposito_detallecompra_liquidado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidaciondeposito',
            options={},
        ),
    ]
