# Generated by Django 6.0.5 on 2026-09-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_estado_solicitudeliminacioncompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='es_vale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquidaciondeposito',
            name='es_vale',
            field=models.BooleanField(default=False),
        ),
    ]