# Generated by Django 6.0.5 on 2026-05-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_liquidaciondeposito_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidaciondeposito',
            options={'ordering': ['-fecha'], 'verbose_name': 'Liquidación de Depósito', 'verbose_name_plural': 'Liquidaciones de Depósito'},
        ),
    ]
